"""add email verification status

Revision ID: 010499f3bc12
Revises: 29050702bab9
Create Date: 2026-08-10 14:39:28.041671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010499f3bc12'
down_revision: Union[str, Sequence[str], None] = '29050702bab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'is_email_verified',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
