"""create login activity table

Revision ID: 29050702bab9
Revises: deda2fdbd283
Create Date: 2026-08-10 09:47:55.108682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29050702bab9'
down_revision: Union[str, Sequence[str], None] = 'deda2fdbd283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'login_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('device', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('login_at', sa.DateTime(), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_login_activities_id'),
        'login_activities',
        ['id'],
        unique=False
    )

    op.create_index(
        op.f('ix_login_activities_user_id'),
        'login_activities',
        ['user_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'hackathons',
    'short_description',
    existing_type=sa.TEXT(),
    nullable=True
)
    op.drop_index(op.f('ix_login_activities_user_id'), table_name='login_activities')
    op.drop_index(op.f('ix_login_activities_id'), table_name='login_activities')
    op.drop_table('login_activities')
    # ### end Alembic commands ###
