"""add unique constraint to team_members

Revision ID: 642023a43d06
Revises: 6b908832ddc2
Create Date: 2026-08-06 06:35:32.079337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642023a43d06'
down_revision: Union[str, Sequence[str], None] = '6b908832ddc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_member', 'team_members', ['team_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_member', 'team_members', type_='unique')
    # ### end Alembic commands ###
