"""add short_description and status to hackathons

Revision ID: 720eb5233572
Revises: 507da8997488
Create Date: 2026-08-07 17:41:35.311893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720eb5233572'
down_revision: Union[str, Sequence[str], None] = '507da8997488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'hackathons',
    sa.Column(
        'short_description',
        sa.Text(),
        nullable=True
    )
)
    op.add_column(
    'hackathons',
    sa.Column(
        'status',
        sa.String(length=20),
        nullable=False,
        server_default='draft'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'status')
    op.drop_column('hackathons', 'short_description')
    # ### end Alembic commands ###
