"""create hackathons table

Revision ID: 92e162c755f6
Revises: 3b2ae0365c53
Create Date: 2026-08-05 18:40:33.972972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e162c755f6'
down_revision: Union[str, Sequence[str], None] = '3b2ae0365c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('prize_pool', sa.String(), nullable=True),
    sa.Column('max_team_size', sa.Integer(), nullable=True),
    sa.Column('registration_link', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathons_id'), 'hackathons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathons_id'), table_name='hackathons')
    op.drop_table('hackathons')
    # ### end Alembic commands ###
